theme: jekyll-theme-cayman

email: "srtaylor@caltech.edu"

title: "The NANOGrav 11-year Data Set: \n Pulsar-timing Constraints On The Stochastic Gravitational-wave Background"

description: A companion website describing the results of our gravitational-wave searches, and how to replicate our analysis.

baseurl: "/11yr_stochastic_analysis"
url: "https://nanograv.github.io"
twitter_username: NANOGrav
github_username:  nanograv